-- Supabase shared workspace migration for Levain Lab.
-- Run this after the public launch/auth setup has already been applied.
-- Phase 1 scope:
-- - personal workspace for every existing user
-- - one general shared workspace per user at most
-- - email pre-registration based membership
-- - workspace_id ownership for recipes, cost_items, temp_logs, deleted_items
-- Company/B2B, shared devices, and Stripe are intentionally excluded here.

create extension if not exists pgcrypto with schema extensions;

do $$
begin
  create type public.workspace_type as enum ('personal', 'shared', 'company');
exception
  when duplicate_object then null;
end $$;

do $$
begin
  create type public.workspace_role as enum ('owner', 'member', 'admin', 'staff');
exception
  when duplicate_object then null;
end $$;

create table if not exists public.workspaces (
  id uuid primary key default gen_random_uuid(),
  type public.workspace_type not null default 'personal',
  name text not null,
  owner_user_id uuid not null references auth.users(id) on delete cascade,
  is_active boolean not null default true,
  created_at timestamptz not null default now(),
  updated_at timestamptz not null default now(),
  constraint workspaces_name_not_blank_check
    check (length(trim(name)) > 0)
);

create table if not exists public.workspace_members (
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  user_id uuid not null references auth.users(id) on delete cascade,
  email text not null,
  role public.workspace_role not null default 'member',
  is_active boolean not null default true,
  joined_at timestamptz not null default now(),
  removed_at timestamptz null,
  primary key (workspace_id, user_id)
);

create table if not exists public.workspace_email_invites (
  id bigint generated by default as identity primary key,
  workspace_id uuid not null references public.workspaces(id) on delete cascade,
  email text not null,
  role public.workspace_role not null default 'member',
  created_by uuid not null references auth.users(id) on delete cascade default auth.uid(),
  created_at timestamptz not null default now(),
  revoked_at timestamptz null,
  constraint workspace_email_invites_email_not_blank_check
    check (length(trim(email)) > 0)
);

create unique index if not exists workspaces_one_personal_per_owner_idx
on public.workspaces(owner_user_id)
where type = 'personal' and is_active = true;

create unique index if not exists workspaces_one_shared_per_owner_idx
on public.workspaces(owner_user_id)
where type = 'shared' and is_active = true;

create unique index if not exists workspace_email_invites_active_email_idx
on public.workspace_email_invites(lower(email))
where revoked_at is null;

create index if not exists workspace_members_user_id_idx
on public.workspace_members(user_id);

create index if not exists workspace_email_invites_workspace_id_idx
on public.workspace_email_invites(workspace_id);

create index if not exists workspace_email_invites_created_by_idx
on public.workspace_email_invites(created_by);

alter table public.recipes
  add column if not exists workspace_id uuid null references public.workspaces(id) on delete cascade;

alter table public.cost_items
  add column if not exists workspace_id uuid null references public.workspaces(id) on delete cascade;

alter table public.temp_logs
  add column if not exists workspace_id uuid null references public.workspaces(id) on delete cascade;

alter table public.deleted_items
  add column if not exists workspace_id uuid null references public.workspaces(id) on delete cascade;

drop index if exists recipes_workspace_id_id_idx;
create unique index recipes_workspace_id_id_idx
on public.recipes(workspace_id, id);

drop index if exists cost_items_workspace_id_id_idx;
create unique index cost_items_workspace_id_id_idx
on public.cost_items(workspace_id, id);

drop index if exists temp_logs_workspace_id_id_idx;
create unique index temp_logs_workspace_id_id_idx
on public.temp_logs(workspace_id, id);

drop index if exists deleted_items_workspace_item_idx;
create unique index deleted_items_workspace_item_idx
on public.deleted_items(workspace_id, item_type, item_id);

alter table public.workspaces enable row level security;
alter table public.workspace_members enable row level security;
alter table public.workspace_email_invites enable row level security;

grant select, insert, update, delete on public.workspaces to authenticated;
grant select, insert, update, delete on public.workspace_members to authenticated;
grant select, insert, update, delete on public.workspace_email_invites to authenticated;
grant usage, select on sequence public.workspace_email_invites_id_seq to authenticated;

create or replace function private.is_workspace_member(target_workspace_id uuid)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members as members
    join public.workspaces as workspaces
      on workspaces.id = members.workspace_id
    where members.workspace_id = target_workspace_id
      and members.user_id = (select auth.uid())
      and members.is_active = true
      and workspaces.is_active = true
  );
$$;

revoke all on function private.is_workspace_member(uuid) from public, anon, authenticated;
grant execute on function private.is_workspace_member(uuid) to authenticated;

create or replace function private.can_manage_workspace(target_workspace_id uuid)
returns boolean
language sql
security definer
set search_path = ''
as $$
  select exists (
    select 1
    from public.workspace_members as members
    join public.workspaces as workspaces
      on workspaces.id = members.workspace_id
    where members.workspace_id = target_workspace_id
      and members.user_id = (select auth.uid())
      and members.is_active = true
      and workspaces.is_active = true
      and members.role in ('owner'::public.workspace_role, 'admin'::public.workspace_role)
  );
$$;

revoke all on function private.can_manage_workspace(uuid) from public, anon, authenticated;
grant execute on function private.can_manage_workspace(uuid) to authenticated;

create or replace function private.prevent_multiple_non_personal_workspaces()
returns trigger
language plpgsql
security definer
set search_path = ''
as $$
declare
  next_workspace_type public.workspace_type;
begin
  if new.is_active is not true then
    return new;
  end if;

  select type
  into next_workspace_type
  from public.workspaces
  where id = new.workspace_id;

  if next_workspace_type in ('shared'::public.workspace_type, 'company'::public.workspace_type)
    and exists (
      select 1
      from public.workspace_members as members
      join public.workspaces as workspaces
        on workspaces.id = members.workspace_id
      where members.user_id = new.user_id
        and members.workspace_id <> new.workspace_id
        and members.is_active = true
        and workspaces.is_active = true
        and workspaces.type in ('shared'::public.workspace_type, 'company'::public.workspace_type)
    )
  then
    raise exception 'Only one shared or company workspace membership is allowed.';
  end if;

  return new;
end;
$$;

revoke all on function private.prevent_multiple_non_personal_workspaces() from public, anon, authenticated;

drop trigger if exists on_workspace_members_prevent_multiple_non_personal on public.workspace_members;
create trigger on_workspace_members_prevent_multiple_non_personal
before insert or update on public.workspace_members
for each row execute function private.prevent_multiple_non_personal_workspaces();

create or replace function public.ensure_personal_workspace()
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  v_workspace_id uuid;
  user_email text;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;

  select email
  into user_email
  from auth.users
  where id = (select auth.uid());

  select id
  into v_workspace_id
  from public.workspaces
  where owner_user_id = (select auth.uid())
    and type = 'personal'::public.workspace_type
    and is_active = true
  limit 1;

  if v_workspace_id is null then
    insert into public.workspaces (type, name, owner_user_id)
    values ('personal'::public.workspace_type, '개인 페이지', (select auth.uid()))
    returning id into v_workspace_id;
  end if;

  insert into public.workspace_members (workspace_id, user_id, email, role, is_active)
  values (v_workspace_id, (select auth.uid()), coalesce(user_email, ''), 'owner'::public.workspace_role, true)
  on conflict (workspace_id, user_id) do update
  set
    email = excluded.email,
    role = 'owner'::public.workspace_role,
    is_active = true,
    removed_at = null;

  update public.recipes
  set workspace_id = v_workspace_id
  where user_id = (select auth.uid())
    and workspace_id is null;

  update public.cost_items
  set workspace_id = v_workspace_id
  where user_id = (select auth.uid())
    and workspace_id is null;

  update public.temp_logs
  set workspace_id = v_workspace_id
  where user_id = (select auth.uid())
    and workspace_id is null;

  update public.deleted_items
  set workspace_id = v_workspace_id
  where user_id = (select auth.uid())
    and workspace_id is null;

  return v_workspace_id;
end;
$$;

revoke execute on function public.ensure_personal_workspace() from authenticated, anon, public;
grant execute on function public.ensure_personal_workspace() to authenticated;

create or replace function public.create_shared_workspace(workspace_name text)
returns uuid
language plpgsql
security definer
set search_path = ''
as $$
declare
  workspace_id uuid;
  user_email text;
  normalized_workspace_name text;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;

  if exists (
    select 1
    from public.workspace_members as members
    join public.workspaces as workspaces
      on workspaces.id = members.workspace_id
    where members.user_id = (select auth.uid())
      and members.is_active = true
      and workspaces.is_active = true
      and workspaces.type in ('shared'::public.workspace_type, 'company'::public.workspace_type)
  ) then
    raise exception 'Only one shared or company workspace membership is allowed.';
  end if;

  select email
  into user_email
  from auth.users
  where id = (select auth.uid());

  normalized_workspace_name := nullif(left(trim(coalesce(workspace_name, '')), 60), '');

  if normalized_workspace_name is null then
    raise exception 'Workspace name is required.';
  end if;

  insert into public.workspaces (type, name, owner_user_id)
  values ('shared'::public.workspace_type, normalized_workspace_name, (select auth.uid()))
  returning id into workspace_id;

  insert into public.workspace_members (workspace_id, user_id, email, role, is_active)
  values (workspace_id, (select auth.uid()), coalesce(user_email, ''), 'owner'::public.workspace_role, true);

  return workspace_id;
end;
$$;

revoke execute on function public.create_shared_workspace(text) from authenticated, anon, public;
grant execute on function public.create_shared_workspace(text) to authenticated;

create or replace function public.accept_workspace_invites_for_current_user()
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  user_email text;
  invite record;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;

  select email
  into user_email
  from auth.users
  where id = (select auth.uid());

  if user_email is null then
    return;
  end if;

  if exists (
    select 1
    from public.workspace_members as members
    join public.workspaces as workspaces
      on workspaces.id = members.workspace_id
    where members.user_id = (select auth.uid())
      and members.is_active = true
      and workspaces.is_active = true
      and workspaces.type in ('shared'::public.workspace_type, 'company'::public.workspace_type)
  ) then
    return;
  end if;

  for invite in
    select invites.workspace_id, invites.role
    from public.workspace_email_invites as invites
    join public.workspaces as workspaces
      on workspaces.id = invites.workspace_id
    where lower(invites.email) = lower(user_email)
      and invites.revoked_at is null
      and workspaces.is_active = true
      and workspaces.type in ('shared'::public.workspace_type, 'company'::public.workspace_type)
    order by invites.created_at asc
    limit 1
  loop
    insert into public.workspace_members (workspace_id, user_id, email, role, is_active)
    values (invite.workspace_id, (select auth.uid()), user_email, coalesce(invite.role, 'member'::public.workspace_role), true)
    on conflict (workspace_id, user_id) do update
    set
      email = excluded.email,
      role = excluded.role,
      is_active = true,
      removed_at = null;
  end loop;
end;
$$;

revoke execute on function public.accept_workspace_invites_for_current_user() from authenticated, anon, public;
grant execute on function public.accept_workspace_invites_for_current_user() to authenticated;

create or replace function public.revoke_workspace_invite(invite_id bigint)
returns void
language plpgsql
security definer
set search_path = ''
as $$
declare
  target_invite record;
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;

  select id, workspace_id, email
  into target_invite
  from public.workspace_email_invites
  where id = invite_id;

  if target_invite.id is null then
    return;
  end if;

  if not (select private.can_manage_workspace(target_invite.workspace_id)) then
    raise exception 'Workspace management permission is required.';
  end if;

  update public.workspace_email_invites
  set revoked_at = coalesce(revoked_at, now())
  where id = target_invite.id;

  update public.workspace_members
  set
    is_active = false,
    removed_at = now()
  where workspace_id = target_invite.workspace_id
    and lower(email) = lower(target_invite.email)
    and role <> 'owner'::public.workspace_role;
end;
$$;

revoke execute on function public.revoke_workspace_invite(bigint) from authenticated, anon, public;
grant execute on function public.revoke_workspace_invite(bigint) to authenticated;

-- Repair already-revoked invite rows from earlier migration attempts:
-- a revoked email should not remain an active workspace member.
update public.workspace_members as members
set
  is_active = false,
  removed_at = coalesce(members.removed_at, invites.revoked_at, now())
from public.workspace_email_invites as invites
where members.workspace_id = invites.workspace_id
  and lower(members.email) = lower(invites.email)
  and members.role <> 'owner'::public.workspace_role
  and members.is_active = true
  and invites.revoked_at is not null;

drop function if exists public.deactivate_shared_workspace(uuid);

create or replace function public.delete_shared_workspace(target_workspace_id uuid)
returns void
language plpgsql
security definer
set search_path = ''
as $$
begin
  if (select auth.uid()) is null then
    raise exception 'Authentication is required.';
  end if;

  delete from public.workspaces
  where id = target_workspace_id
    and type = 'shared'::public.workspace_type
    and owner_user_id = (select auth.uid());

  if not found then
    raise exception 'Shared workspace owner permission is required.';
  end if;
end;
$$;

revoke execute on function public.delete_shared_workspace(uuid) from authenticated, anon, public;
grant execute on function public.delete_shared_workspace(uuid) to authenticated;

insert into public.workspaces (type, name, owner_user_id)
select 'personal'::public.workspace_type, '개인 페이지', users.id
from auth.users as users
where not exists (
  select 1
  from public.workspaces
  where owner_user_id = users.id
    and type = 'personal'::public.workspace_type
);

insert into public.workspace_members (workspace_id, user_id, email, role, is_active)
select workspaces.id, users.id, users.email, 'owner'::public.workspace_role, true
from auth.users as users
join public.workspaces as workspaces
  on workspaces.owner_user_id = users.id
 and workspaces.type = 'personal'::public.workspace_type
on conflict (workspace_id, user_id) do update
set
  email = excluded.email,
  role = 'owner'::public.workspace_role,
  is_active = true,
  removed_at = null;

update public.recipes as recipes
set workspace_id = workspaces.id
from public.workspaces as workspaces
where recipes.workspace_id is null
  and recipes.user_id = workspaces.owner_user_id
  and workspaces.type = 'personal'::public.workspace_type;

update public.cost_items as cost_items
set workspace_id = workspaces.id
from public.workspaces as workspaces
where cost_items.workspace_id is null
  and cost_items.user_id = workspaces.owner_user_id
  and workspaces.type = 'personal'::public.workspace_type;

update public.temp_logs as temp_logs
set workspace_id = workspaces.id
from public.workspaces as workspaces
where temp_logs.workspace_id is null
  and temp_logs.user_id = workspaces.owner_user_id
  and workspaces.type = 'personal'::public.workspace_type;

update public.deleted_items as deleted_items
set workspace_id = workspaces.id
from public.workspaces as workspaces
where deleted_items.workspace_id is null
  and deleted_items.user_id = workspaces.owner_user_id
  and workspaces.type = 'personal'::public.workspace_type;

alter table public.deleted_items
  drop constraint if exists deleted_items_pkey;

alter table public.deleted_items
  add constraint deleted_items_pkey
  primary key (workspace_id, user_id, item_type, item_id);

drop policy if exists "Workspace members can view workspaces" on public.workspaces;
create policy "Workspace members can view workspaces"
on public.workspaces
for select
to authenticated
using ((select private.is_workspace_member(id)));

drop policy if exists "Users can insert their own personal workspace" on public.workspaces;
create policy "Users can insert their own personal workspace"
on public.workspaces
for insert
to authenticated
with check (
  owner_user_id = (select auth.uid())
  and type = 'personal'::public.workspace_type
);

drop policy if exists "Workspace managers can update workspaces" on public.workspaces;
create policy "Workspace managers can update workspaces"
on public.workspaces
for update
to authenticated
using ((select private.can_manage_workspace(id)))
with check ((select private.can_manage_workspace(id)));

drop policy if exists "Workspace members can view members" on public.workspace_members;
create policy "Workspace members can view members"
on public.workspace_members
for select
to authenticated
using ((select private.is_workspace_member(workspace_id)));

drop policy if exists "Workspace managers can manage members" on public.workspace_members;
drop policy if exists "Workspace managers can insert members" on public.workspace_members;
drop policy if exists "Workspace managers can update members" on public.workspace_members;
drop policy if exists "Workspace managers can delete members" on public.workspace_members;
create policy "Workspace managers can insert members"
on public.workspace_members
for insert
to authenticated
with check ((select private.can_manage_workspace(workspace_id)));

create policy "Workspace managers can update members"
on public.workspace_members
for update
to authenticated
using ((select private.can_manage_workspace(workspace_id)))
with check ((select private.can_manage_workspace(workspace_id)));

create policy "Workspace managers can delete members"
on public.workspace_members
for delete
to authenticated
using ((select private.can_manage_workspace(workspace_id)));

drop policy if exists "Workspace members can view invites" on public.workspace_email_invites;
drop policy if exists "Workspace managers can view invites" on public.workspace_email_invites;
create policy "Workspace managers can view invites"
on public.workspace_email_invites
for select
to authenticated
using ((select private.can_manage_workspace(workspace_id)));

drop policy if exists "Workspace managers can manage invites" on public.workspace_email_invites;
drop policy if exists "Workspace managers can insert invites" on public.workspace_email_invites;
drop policy if exists "Workspace managers can update invites" on public.workspace_email_invites;
drop policy if exists "Workspace managers can delete invites" on public.workspace_email_invites;
create policy "Workspace managers can insert invites"
on public.workspace_email_invites
for insert
to authenticated
with check ((select private.can_manage_workspace(workspace_id)));

create policy "Workspace managers can update invites"
on public.workspace_email_invites
for update
to authenticated
using ((select private.can_manage_workspace(workspace_id)))
with check ((select private.can_manage_workspace(workspace_id)));

create policy "Workspace managers can delete invites"
on public.workspace_email_invites
for delete
to authenticated
using ((select private.can_manage_workspace(workspace_id)));

drop policy if exists "Users can view their own recipes" on public.recipes;
create policy "Users can view their own recipes"
on public.recipes
for select
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can insert their own recipes" on public.recipes;
create policy "Users can insert their own recipes"
on public.recipes
for insert
to authenticated
with check (
  (
    workspace_id is not null
    and user_id = (select auth.uid())
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can update their own recipes" on public.recipes;
create policy "Users can update their own recipes"
on public.recipes
for update
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
)
with check (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can delete their own recipes" on public.recipes;
create policy "Users can delete their own recipes"
on public.recipes
for delete
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can view their own cost items" on public.cost_items;
create policy "Users can view their own cost items"
on public.cost_items
for select
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can insert their own cost items" on public.cost_items;
create policy "Users can insert their own cost items"
on public.cost_items
for insert
to authenticated
with check (
  (
    workspace_id is not null
    and user_id = (select auth.uid())
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can update their own cost items" on public.cost_items;
create policy "Users can update their own cost items"
on public.cost_items
for update
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
)
with check (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can delete their own cost items" on public.cost_items;
create policy "Users can delete their own cost items"
on public.cost_items
for delete
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can view their own temp logs" on public.temp_logs;
create policy "Users can view their own temp logs"
on public.temp_logs
for select
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can insert their own temp logs" on public.temp_logs;
create policy "Users can insert their own temp logs"
on public.temp_logs
for insert
to authenticated
with check (
  (
    workspace_id is not null
    and user_id = (select auth.uid())
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can update their own temp logs" on public.temp_logs;
create policy "Users can update their own temp logs"
on public.temp_logs
for update
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
)
with check (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can delete their own temp logs" on public.temp_logs;
create policy "Users can delete their own temp logs"
on public.temp_logs
for delete
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can view their own deleted items" on public.deleted_items;
create policy "Users can view their own deleted items"
on public.deleted_items
for select
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can insert their own deleted items" on public.deleted_items;
create policy "Users can insert their own deleted items"
on public.deleted_items
for insert
to authenticated
with check (
  (
    workspace_id is not null
    and user_id = (select auth.uid())
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);

drop policy if exists "Users can update their own deleted items" on public.deleted_items;
create policy "Users can update their own deleted items"
on public.deleted_items
for update
to authenticated
using (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
)
with check (
  (
    workspace_id is not null
    and (select private.is_workspace_member(workspace_id))
    and (select private.has_app_access())
  )
  or (
    workspace_id is null
    and user_id = (select auth.uid())
    and (select private.has_app_access())
  )
);
